---
title: "Tidyverse"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(dslabs)
```

```{r}
murders <- mutate(murders, rate=total/population*100000)
```

```{r}
filter(murders, rate <= 0.71)
```

```{r}
new_table <- select(murders, state, region, rate)
filter(new_table, rate <= 0.71)
```

```{r}
murders %>% select(state, region, rate) %>% filter(rate <= 0.71)
```

```{r}
murders %>% summarize(avg = mean(rate))
```

```{r}
# n = n() - counts number of observations in a grouped dplyr dataframe 
```

## EXERCISE 1

```{r}
murders %>% filter(rate < 1)
```

## EXERCISE 2

```{r}
murders %>% filter(rate < 1 & region == "West") %>% select(state, abb, population, total, rate)
```

## 3

```{r}
murders %>% filter(rate < 1) %>% slice_max(population)
```

## 4

```{r}
murders %>% filter(population > 10^7) %>% slice_min(rate)
```


## 5

```{r}
murders %>% group_by(region) %>% summarize()
```

## Part 2

```{r}
library(NHANES)
?NHANES
```

```{r}
NHANES %>% filter(!is.na(Race1) & !is.na(Race3)) %>% filter(as.character(Race1) != as.character(Race3)) %>% count(Race1, Race3)
```

```{r}
dat <- NHANES %>% mutate(Race=Race3) %>% mutate(Race = if_else(is.na(Race), Race1, Race))
```

```{r}
with(NHANES, table(Race1, Race3, useNA = 'always'))
```

```{r}
dat %>% group_by(Gender, Race) %>% summarize(n = sum(!is.na(Smoke100)), smoke = sum(SmokeNow == "Yes", na.rm = TRUE)) %>% mutate(smoke = smoke/n) %>% arrange(n)
```
